### ISSUE TITLE
Вопрос по оформлению

### ISSUE THREAD

**Issue by daniilkrichevskiy** [altwarg/LaTeX-GOST-BMSTU-Diploma#2]
Добрый вечер! Спасибо большое за шаблон!
Подскажите, пожалуйста,
1) как изменить цвет ссылок на источник (использую в разделе \section*{СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ} функцию \begin{thebibliography}) - они у меня почему-то зелёные (\cite{имя источника})?
2) при использовании \begin{thebibliography} после заголовка СПИСОК ИСПОЛЬЗОВАННЫХ ИСТОЧНИКОВ появляется лишняя надпись "Список литературы". как её убрать?

Спасибо

**Comment by altwarg** [comment]
Добрый вечер, @daniilkrichevskiy. Надеюсь, ответ еще актуален.

Насчет ссылок используется пакет `color`.
Для гиперссылок, что я использовал в преамбуле настраивается цвет:
```
\hypersetup{
     linktoc=all,
     linkcolor=black, % Цвет
     colorlinks=true,
}
```

Для библиографии, по тому, что я увидел в документации пакета, используется `\section*{\refname}`. Чтобы убрать название, думаю, можно переопределить этот `\section` как-то так:

```tex
\documentclass{article}

\begin{document}
   \begingroup
      \renewcommand{\section}[2]{}
      \begin{thebibliography}{}
         ...
      \end{thebibliography}
   \endgroup
\end{document}
```
