### ISSUE TITLE
Где найти сам шаблон диплома

### ISSUE THREAD

**Issue by inspired99** [altwarg/LaTeX-GOST-BMSTU-Diploma#3]
Здравствуйте, если еще отвечаете на вопросы, не подскажите где найти сам шаблон диплома, так как на данный момент загружен календарный план, записка и задание, однако шаблона для диплома нет. Спасибо!

**Comment by altwarg** [comment]
@inspired99, это шаблон РПЗ (расчетно-пояснительной записки).

Когда писал диплом, часть **описываемая мной**:
- Задания на ВКР (малый лист, двухсторонний, вшивался в расчетно-пояснительную записку вторым листом)
- Расчетно-пояснительной записки, в которой и описывался диплом
- Графической части (листы формата А1)
- Календарный план (прикладывался отдельно)
- Приложения (техническое задание, руководства и прочее)
- Справка о внедрении
- Внешняя рецензия

В то же время были части диплома, выдаваемые со стороны университета;
- Акт о прохождении нормоконтроля (проверка на ГОСТы)
- Направление на защиту ВКР

Из того, что я описал, в репозитории есть:
- Шаблон РПЗ
- Шаблон календарного плана
- Шаблон задания на ВКР

Приложения, справка о внедрении, внешняя рецензия имеют свободную форму, графическая часть задается без использования LaTeX. Остальное необходимое в репозитории присутствует. Надеюсь, ответит на вопрос полно.
